<script type="text/javascript" src="js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<div id="tips">
	<h5>
		<a class="active"><?= $this->greeting ?></a>
		<a>Hi!</a>
	</h5>
</div>
<section id="main">
	<article>
		<div id="title">Password recovery - Step 1</div>
		<div id="message">Password reset confirmation link has been sent to you by e-mail</div>
		<ul class="list">
			<li><a href="#">List 1</a></li>
			<li><a href="#">List 2</a></li>
			<li><a href="#">List 3</a></li>
			<li><a href="#">List 4</a></li>
			<li><a href="#">List 5</a></li>
		</ul>
	</article>
	
	<article>
	
		<div class="accordion"> 
			<section class="acc" id="one"> 
				<h2><a href="#one">Heading 1</a></h2> 
				<div> 
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</p> 
				</div> 
			</section> 
			<section class="acc" id="two"> 
				<h2><a href="#two">Heading 2</a></h2> 
				<div> 
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</p> 
				</div> 
			</section> 					
			<section class="acc" id="three"> 
				<h2><a href="#three">Heading 3</a></h2> 
				<div> 
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</p> 
				</div> 
			</section> 					
			<section class="acc" id="four"> 
				<h2><a href="#four">Heading 4</a></h2> 
				<div> 
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>										
				</div> 
			</section> 					
			<section class="acc" id="five"> 
				<h2><a href="#five">Heading 5</a></h2> 
				<div> 
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</p> 
				</div> 
			</section> 
		</div>
		
		<aside class="note"> 
			<h3>КНДР заподозрили в новых испытаниях ракет дальнего радиуса</h3>
			<p>КНДР в октябре 2010 года провела новые испытания ракет дальнего радиуса действия на одном из полигонов на северо-западе страны. Тесты были проведены, предположительно, специально в тот день, когда спутники США могли отследить запуски. Ранее информации о тестовых пусках ракет Северной Кореей в 2010 году не поступало.</p>
		</aside>
		
	</article> 
</section>