<div id="tips">
    <h5>
        <a class="profile" href="/user/profile">Details</a>
        <a class="bank" href="/user/bank">Finances</a>
        <a class="address" href="/user/address">Address</a>
        <a class="settings" href="/user/settings">Settings</a>
        <a class="subscribe" href="/user/subscribe">Subscribtion</a>
        <a class="stats" href="/user/stats">Stats</a>
    </h5>
</div>