<link rel="stylesheet" href="/css/user.css">
<script src="/js/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript"> 
    $(document).ready(function() {
        $("#login").validate();
        $("#username").rules("add", {required:true, rangelength: [5, 20]});
        $("#password").rules("add", {required:true, rangelength: [6, 20]});
    });
</script>

<section id="main" class="login">
    <div class="title">Sign In</div>
    <?php 
        echo $this->error;
        echo $this->form;
    ?>
    <div class="links">
        <a href="/user/account/signup">Register account</a> |
        <a href="/user/account/recover">Forgot password?</a>
    </div>
</section>