<link rel="stylesheet" href="/css/user.css">
<script src="/js/jquery.validate.min.js" type="text/javascript"></script>
<script type="text/javascript"> 
    $(document).ready(function() {
        $("#recover").validate();
        $("#email").rules("add", {required:true});
    });
</script>

<section id="main">
    <div class="title">Recover password</div>
    <?php 
        echo $this->error;
        echo $this->form;
    ?>
</section>